### ISSUE TITLE
Random crashes while running

### ISSUE THREAD

**Issue by HASJ** [itsmrpeck/sglobbylink-discord.py#2]
```
Task was destroyed but it is pending!
task: <Task pending coro=<clear_request_counts_once_per_day() done, defined at D:\SGBRbot\SGBRbot.py:123> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002B46BB97498>()]>>
```

This is the latest one.

**Comment by itsmrpeck** [comment]
It looks like this could be caused by this Discord.py issue that happens if you run the bot on an unresponsive machine or under heavy CPU load: https://github.com/Rapptz/discord.py/issues/101

**Comment by itsmrpeck** [comment]
Version 1.3 no longer blocks the main thread while making HTTP requests or writing to steam_ids.txt. Let me know if that fixes the issue.

**Comment by itsmrpeck** [comment]
Closing this issue for now. Let me know if it still happens!
